apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }} #postgresdb
spec:
  replicas: {{ .Values.deploy.replicas }} #1
  selector:
    matchLabels:
      app: {{ .Values.deploy.selector.app }} #postgresdb
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.labels.app }} #postgresdb
    spec:
      containers:
      - name: {{ .Values.deploy.containers.name }} #postgresdb
        image: {{ .Values.deploy.containers.image }} #postgres:latest
        ports:
        - containerPort: {{ .Values.deploy.containers.containerPort }} #5432
        envFrom:
        - secretRef:
            name: {{ .Values.deploy.containers.envFrom.name }} #secret-env-config
        volumeMounts:
          - name: {{ .Values.deploy.containers.volumeMounts.name }} #database
            mountPath: {{ .Values.deploy.containers.volumeMounts.mountPath }} #/var/lib/postgresql
            subPath: {{ .Values.deploy.containers.volumeMounts.subPath }} #backup
      volumes:
        - name: {{ .Values.deploy.volumes.name }} #database
          persistentVolumeClaim:
            claimName: {{ .Values.deploy.volumes.persistentVolumeClaim.claimName }} #pvc-postgres