apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }} #pvc-postgres
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }} #ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName }} #managed-premium
  resources:
    requests:
      storage: {{ .Values.pvc.storage }} #10Gi
