apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.target }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  -  http:
      paths:
        - path: {{ .Values.ingress.rules.path }}
          pathType: {{ .Values.ingress.rules.pathType }}
          backend:
            service:
              name: {{ .Values.ingress.backend.service.name }}
              port:
                number: {{ .Values.ingress.backend.service.port.number }}